# Generated by Django 3.2.7 on 2021-09-17 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pays')),
            ],
        ),
        migrations.CreateModel(
            name='Employés',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_employe', models.IntegerField()),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marques')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ville')),
            ],
        ),
    ]
